### ISSUE TITLE
stremio-server.json missing

### ISSUE THREAD

**Issue by Makanz** [sleeyax/stremio-streaming-server#13] opened 2022-07-17 21:08 UTC
Found that the settings file server-settings.json is missing when starting up the image.

Solved it by creating a json file manually. 
Is it possible to add a command in start.sh to create a settings file if it´s missing?

**Comment by sleeyax** [comment] 2022-07-17 21:46
The settings file gets created on startup at the path `/root/.stremio-server/server-settings.json`. You can find it on your host machine as well, depending on where you mounted the volume. For example, if you bind the volume with  `-v /var/tmp/stremio:/root/.stremio-server`, then you should find the settings file at `/var/tmp/stremio/server-settings.json` on your host after running the container for the first time.

**Comment by Makanz** [comment] 2022-07-17 21:53
I did that but the file was not created.

Created a docker-compose file:

```
version: "3"

services:
  stremio-server:
    image: sleeyax/stremio-streaming-server
    container_name: stremio-server
    restart: unless-stopped
    environment:
      - FIX_CORS=1
    ports:
      - 11470:11470
    volumes:
      - /mnt/MD0-DATA/docker/stremio-server:/root/.stremio-server
```
![error_message](https://user-images.githubusercontent.com/4232943/179426202-dd97942f-03b4-401a-bef9-0c8bfb0b2d47.png)

**Comment by sleeyax** [comment] 2022-07-17 23:38
Hm maybe it's only created when you start to play some media in Stremio, connected to this streaming server instance?

**Comment by Makanz** [comment] 2022-07-18 19:54
If I create the file manually it get written to on startup.

**Comment by sleeyax** [comment] 2022-07-18 20:12
Ok but the point is it shouldn't be required to manually create a file... I never did so and got the settings file just fine.
________________________________

**Comment by sleeyax** [comment] 2022-08-03 23:39
Closing this issue because I still can't reproduce it ¯\_(ツ)_/¯  .

Most likely a faulty volume was specified. Try specifying a valid volume path on the host and make sure it has the right permissions to write to it (e.g.  `/var/tmp/stremio` on linux).

**Closed as completed by sleeyax** 2022-08-03 23:39 UTC
Labels: question
